language: node_js
node_js:
- '0.10'
before_install:
- npm install -g gulp
before_script:
- gulp build
after_success:
- gulp deploy
notifications:
  hipchat:
    rooms:
      secure: RGIWsvAU4zBQDQxgtiFonggOkOKMuFmavmdpr1U+IexIZEI7cWn9oZUpuI1K6lC/WXRNfS0ldCPjdA22+cNzYVa5cTIaDiO4BVnwsDhVc9QrOdvgUl86hGOAoLBwo1DoKsdjfDPoB6mIzI21vxie+l50hzQokWWKCjeQCfoR3FA=
    template:
    - '<a href="%{build_url}">%{branch}</a> - <a href="%{compare_url}">%{commit}</a>
      : %{message}'
    format: html
env:
  global:
  - namespace: 'external'
  - secure: HpaInFqzg9P5bPVrcbZyR7MsVeWNV/y7bX47jPCFdHkFcZxWcHU5t0ct3LwhlXCWzYPlhOR+frOiHaaPZYVH2NomcYHrtI+Uro1BqfnneKxpQx8Ns0VK83EvKyGyf1hQ7kl8NqAfB3o8tl4dhsSVQT8K2QZzPYlduP40moOUzJI=
  - secure: ABZXu/iUaXgeoG4AEMYMmRO1zFRjlsQgDpYH8HVnalQW970jdQh0+4ehiUUedUoSKr5s1wrtMZXgZiiHKbUyUB49/5eLM3uKbdBi0II3L9n8CqaHqg0oGERwNfxgmmRkAUrhh5NlWoXKlnyojruq2pft2r2SJXAyX7cQLTGZ03M=
  - secure: YmrRHUmCYMol0ZRA6m2TcR2v/HZMwOaIVlFtZtQlHB/WCmncymHO34yPsGzI+bVNFnd/HB4jvtNu0wNDvNvhFz37mIbJ1o/m3pSbBFn9r9nxnP4ULI4ObHE45xXVRCSRShXNCpXE+/RGWDTeq69MjwpwcG4WSyln+/I3aWQMc6w=
  - secure: bpDxN8lSy6H0m+gkAIS7o/cb3yuI+X9BftAiKnweChBT9fh3k0hwK71QXdUDTq3LpZ3SweMFYiG1KxmHlaCK0HGGoZ1Y9HbJYsEknuMLlKGSEHAJVeSN6PkqZBEa0JryYixuNYyu37Bx+NLhFNF7smzKlRI2xcKpZnvshQH+2j0=
